* On the Road to Financial Fitness

** Make wise financial decisions no matter the time of year

** Looking for a resolution that can literally pay off even if you wind up not keeping it? Think: your finances.

** That's right, unlike the other New Year's pledges we make this time of year only to soon break, simply vowing to handle fiscal matters better can have "a positive impact" on your bottom line.

** That's one of the more intriguing findings form Fidelity Investments' New Year Financial Resolutions Study, and it's based on stats like these comparing respondents who said they'd made financial resolutions to those who hadn't:

*** Resolvers beat non-resolvers when it came to ending a year more debt-free than previous year (45 percent versus 34 percent).

*** They also now feel more "financially secure" (45 percent versus 34 percent).

*** And they also feel more optimistic about their finances looking ahead (52 percent versus 37 percent). And those who actually did follow through on their resolutions? Sixty-six percent said they're now "in a better financial situation."

*** "The fact is, people who make resolutions on money matters tends to feel better about the state finances, which helps them stay engaged and make progress toward their goals," says Ken Hevert, Fidelity's senior vice president of retirement.

** What were the top three financial resolutions?

*** Saving more toped the list among those at least considering making a resolution (50 percent), followed by paying down or payhing off debt (28 percent) and spending less (16 percent). And those Americans surveyed had some real concerns. Chief among them: the dreaded "unexpected expenses."

*** "Whether it's a new roof for your home or a medical emergency, the unexpected can throw your finances for a loop says Hevert. "In fact, for those whose resolutions fell short the previous year, almost three-quarters said they were derailed by unforeseen

***
