* Tree Simple Words

** Words that could save your marriage, your career and even your life

*** My family just got back from a wonderful vacation. It was 10 days of good food, great sun and beautiful beaches. One day had the potential to ruin our trip, though. I had caught a bad cold, and was contemplating staying home. But my wife had her heart set on the beach, and since we have three small children, I came along to help out.

** Going along with the plan

*** I thought we might head to the same beach we went to just a few days earlier. But my wife wanted to try a different beach, so I went along with the plan. We arrive, and my wife was in heaven.

*** I wasn't as enthusiastic. The sand wasn't nearly as soft as I like. And the surf was much rougher, which certainly didn't please my 4-year old. As I kept comparing this beach to the other one. my mood deteriorated. And then I remebered three little words that have saved my relationship time and time again: Disagree and commit.

** A healthy way to communicate

*** The principle of "disagree and commit" was created in the 1980s and popularized by companies like Intel and Amazon. It's a management principle that encourages healthy discussion and disagreement during the decision-making process, but that requires ful support for a decision once made . Amazon founder Jef Bezos described it this way: This phrase will save a lot of time. If you have conviction on a particular direction even though there's no consensus, it's helpful to say, "Look, I know we disagree on this, but will you gamble with me on it? Disagree and commit?"

*** In the case of our vacation, I had agreed to let my wife  pick the beach for the day. Because of my cold, I would have found something wrong with just about any beach. And complaining would have just made everyone else miserable too-and undermined my wife at the same time.

*** So, I did the opoosite. I looked for all the great things about the beach and voiced them out loud. And guess what? I survived those few hours on the beach. Most important , I avoided what could have quickly snowballed into disaster--had I not remembered those three little words: Disagree and commit.

** How it can save your life

*** So, how can disagree and commit save your life? Maybe you've heard of the Harvard Study of Adult Development, one of the most comprehensive studies of emotional well-being in history. The study has been running for more than 80 years and has resulted in an abundance of data on physical, mental and emotional health. "The surpring finding is that our relationships and how happy we are in our relationships have a powerful influence on our health", said Robert Waldinger, directior of the study and a professor of pyschiarty at Harvard Medical School. "Taking care of your body is important, but tending to your realtionships is a form of self-care too."

*** So, what does all of this have to do with disagree and commit? In all our relationships, we're looking for support. Of course, good friends should be able to have healthy disagreements. But when it comes time to make dicesions, there are times when all the discussion in the world won't change another person's mind.

*** When that happens, ask yourself: Can I disagree and commit?

*** If you can' you'll show your partner you're willing to go all in---and they'll do the same for you.

*** I know it'saved my most precious relationships countless times over the years. And it's major reason why--after 11 years of marriage, three kids, and even the stress of a family vacation---the relationship between my wife and me is stronger than ever.

